import { VehicleConfig } from './types';

export const VEHICLES: VehicleConfig[] = [
  {
    id: 'bicycle',
    name: 'Bicycle',
    category: 'two_wheeler',
    stats: { maxSpeed: 25, acceleration: 8, handling: 95, weight: 15, brakePower: 60, health: 100 },
    modelKey: 'bicycle',
    sounds: { engine: 'pedal', horn: 'bell', brake: 'brake_soft', collision: 'hit_light', skid: 'skid_light' },
    unlockCost: 0,
    description: 'Light and nimble through city traffic',
  },
  {
    id: 'motorcycle',
    name: 'Motorcycle',
    category: 'two_wheeler',
    stats: { maxSpeed: 120, acceleration: 85, handling: 90, weight: 180, brakePower: 75, health: 100 },
    modelKey: 'motorcycle',
    sounds: { engine: 'bike_engine', horn: 'horn_bike', brake: 'brake_medium', collision: 'hit_medium', skid: 'skid_medium' },
    unlockCost: 500,
    description: 'Fast two-wheeler for weaving through traffic',
  },
  {
    id: 'scooter',
    name: 'Scooter',
    category: 'two_wheeler',
    stats: { maxSpeed: 70, acceleration: 55, handling: 85, weight: 110, brakePower: 65, health: 100 },
    modelKey: 'scooter',
    sounds: { engine: 'scooter_engine', horn: 'horn_scooter', brake: 'brake_soft', collision: 'hit_light', skid: 'skid_light' },
    unlockCost: 0,
    description: 'Popular Indian commuter scooter',
  },
  {
    id: 'auto_rickshaw',
    name: 'Auto Rickshaw',
    category: 'commercial',
    stats: { maxSpeed: 55, acceleration: 40, handling: 70, weight: 350, brakePower: 55, health: 100 },
    modelKey: 'auto_rickshaw',
    sounds: { engine: 'auto_engine', horn: 'horn_auto', brake: 'brake_medium', collision: 'hit_medium', skid: 'skid_medium' },
    unlockCost: 300,
    description: 'The iconic Indian three-wheeler',
  },
  {
    id: 'hatchback',
    name: 'Hatchback Car',
    category: 'car',
    stats: { maxSpeed: 300, acceleration: 92, handling: 78, weight: 1100, brakePower: 88, health: 100 },
    modelKey: 'hatchback',
    sounds: { engine: 'car_small', horn: 'horn_car', brake: 'brake_medium', collision: 'hit_medium', skid: 'skid_medium' },
    unlockCost: 0,
    description: 'Compact city car perfect for urban roads',
  },
  {
    id: 'wagon',
    name: 'Wagon',
    category: 'car',
    stats: { maxSpeed: 300, acceleration: 90, handling: 74, weight: 1600, brakePower: 86, health: 100 },
    modelKey: 'wagon',
    sounds: { engine: 'car_medium', horn: 'horn_car', brake: 'brake_medium', collision: 'hit_medium', skid: 'skid_medium' },
    unlockCost: 0,
    description: 'Spacious family wagon for long highway drives',
  },
  {
    id: 'sedan',
    name: 'Sedan',
    category: 'car',
    stats: { maxSpeed: 300, acceleration: 94, handling: 76, weight: 1400, brakePower: 90, health: 100 },
    modelKey: 'sedan',
    sounds: { engine: 'car_medium', horn: 'horn_car', brake: 'brake_medium', collision: 'hit_medium', skid: 'skid_medium' },
    unlockCost: 800,
    description: 'Comfortable sedan for highway cruising',
  },
  {
    id: 'suv',
    name: 'SUV',
    category: 'car',
    stats: { maxSpeed: 300, acceleration: 88, handling: 68, weight: 2000, brakePower: 90, health: 100 },
    modelKey: 'suv',
    sounds: { engine: 'car_large', horn: 'horn_car', brake: 'brake_heavy', collision: 'hit_heavy', skid: 'skid_heavy' },
    unlockCost: 1500,
    description: 'Powerful SUV for rough terrain',
  },
  {
    id: 'jeep',
    name: 'Jeep',
    category: 'car',
    stats: { maxSpeed: 300, acceleration: 86, handling: 70, weight: 1800, brakePower: 88, health: 100 },
    modelKey: 'jeep',
    sounds: { engine: 'jeep_engine', horn: 'horn_car', brake: 'brake_heavy', collision: 'hit_heavy', skid: 'skid_heavy' },
    unlockCost: 1200,
    description: 'Rugged off-roader for Ladakh mountains',
  },
  {
    id: 'sports_car',
    name: 'Sports Car',
    category: 'car',
    stats: { maxSpeed: 300, acceleration: 98, handling: 90, weight: 1300, brakePower: 95, health: 100 },
    modelKey: 'sports_car',
    sounds: { engine: 'sports_engine', horn: 'horn_sports', brake: 'brake_sport', collision: 'hit_medium', skid: 'skid_sport' },
    unlockCost: 5000,
    description: 'High-performance sports car',
  },
  {
    id: 'formula_car',
    name: 'Formula Car',
    category: 'special',
    stats: { maxSpeed: 300, acceleration: 100, handling: 96, weight: 700, brakePower: 98, health: 100 },
    modelKey: 'formula_car',
    sounds: { engine: 'formula_engine', horn: 'horn_sports', brake: 'brake_sport', collision: 'hit_light', skid: 'skid_sport' },
    unlockCost: 10000,
    description: 'Ultimate racing machine',
  },
  {
    id: 'mini_truck',
    name: 'Mini Truck',
    category: 'commercial',
    stats: { maxSpeed: 90, acceleration: 35, handling: 50, weight: 2500, brakePower: 70, health: 100 },
    modelKey: 'mini_truck',
    sounds: { engine: 'truck_small', horn: 'horn_truck', brake: 'brake_heavy', collision: 'hit_heavy', skid: 'skid_heavy' },
    unlockCost: 600,
    description: 'Small commercial truck for goods transport',
  },
  {
    id: 'lorry',
    name: 'Lorry',
    category: 'commercial',
    stats: { maxSpeed: 80, acceleration: 25, handling: 40, weight: 8000, brakePower: 75, health: 100 },
    modelKey: 'lorry',
    sounds: { engine: 'truck_large', horn: 'horn_truck', brake: 'brake_heavy', collision: 'hit_heavy', skid: 'skid_heavy' },
    unlockCost: 1000,
    description: 'Heavy goods lorry for highways',
  },
  {
    id: 'bus',
    name: 'Bus',
    category: 'commercial',
    stats: { maxSpeed: 100, acceleration: 30, handling: 45, weight: 12000, brakePower: 78, health: 100 },
    modelKey: 'bus',
    sounds: { engine: 'bus_engine', horn: 'horn_bus', brake: 'brake_heavy', collision: 'hit_heavy', skid: 'skid_heavy' },
    unlockCost: 800,
    description: 'Public transport bus',
  },
  {
    id: 'tractor',
    name: 'Tractor',
    category: 'commercial',
    stats: { maxSpeed: 40, acceleration: 20, handling: 55, weight: 3000, brakePower: 60, health: 100 },
    modelKey: 'tractor',
    sounds: { engine: 'tractor_engine', horn: 'horn_tractor', brake: 'brake_medium', collision: 'hit_heavy', skid: 'skid_heavy' },
    unlockCost: 400,
    description: 'Farm tractor for village roads',
  },
  {
    id: 'toy_car',
    name: 'Toy Car',
    category: 'special',
    stats: { maxSpeed: 30, acceleration: 45, handling: 80, weight: 5, brakePower: 40, health: 100 },
    modelKey: 'toy_car',
    sounds: { engine: 'toy_engine', horn: 'horn_toy', brake: 'brake_soft', collision: 'hit_light', skid: 'skid_light' },
    unlockCost: 200,
    description: 'Fun mini car for casual racing',
  },
  {
    id: 'police_car',
    name: 'Police Car',
    category: 'special',
    stats: { maxSpeed: 300, acceleration: 96, handling: 84, weight: 1600, brakePower: 94, health: 100 },
    modelKey: 'police_car',
    sounds: { engine: 'police_engine', horn: 'siren', brake: 'brake_sport', collision: 'hit_medium', skid: 'skid_sport' },
    unlockCost: 3000,
    description: 'Law enforcement pursuit vehicle',
  },
  {
    id: 'ambulance',
    name: 'Ambulance',
    category: 'special',
    stats: { maxSpeed: 280, acceleration: 90, handling: 72, weight: 2200, brakePower: 90, health: 100 },
    modelKey: 'ambulance',
    sounds: { engine: 'ambulance_engine', horn: 'siren_ambulance', brake: 'brake_heavy', collision: 'hit_heavy', skid: 'skid_heavy' },
    unlockCost: 2000,
    description: 'Emergency medical vehicle',
  },
  {
    id: 'pickup_truck',
    name: 'Pickup Truck',
    category: 'commercial',
    stats: { maxSpeed: 130, acceleration: 45, handling: 58, weight: 2200, brakePower: 78, health: 100 },
    modelKey: 'pickup_truck',
    sounds: { engine: 'truck_small', horn: 'horn_truck', brake: 'brake_heavy', collision: 'hit_heavy', skid: 'skid_heavy' },
    unlockCost: 900,
    description: 'Versatile pickup for all terrains',
  },
];

export const DEFAULT_VEHICLE_ID = 'hatchback';

export const VEHICLE_COLORS = [
  '#FF9933', '#FFFFFF', '#138808', '#000080', '#DC143C',
  '#FFD700', '#00CED1', '#FF4500', '#8B008B', '#2F4F4F',
  '#FF69B4', '#1E90FF', '#32CD32', '#FF6347', '#4B0082',
];

export function getVehicleById(id: string): VehicleConfig | undefined {
  return VEHICLES.find((v) => v.id === id);
}
